appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 3Rux1FVEgd93+36m2amKu1Kztuufqyk/CLXcOAXk8IMCZ697KFKuU3IKcyixL468bhGQwzAu8S7t+up5BmWCkAz5a++JfGVegOTjTdsEu5uTu/tdgnkY5GHSPpyKEokwv8s87q8vWdgGEiF7GJ+vQD6LqD4DS0rCQf/gdKk8pMtVScdEf1ynKxBZeWESR5U2F9qpw41S5XdNr3z6wVxorRAr107NMMhthQTAGXQFAdw9JX/WiQdET6jRt8WRTiytgkrr5dkQ/gtNdaT8LzAQknvj/qwTsMfL8bxgOQyZZj+I0XqBkg0WIMw/DfXxzzUAy3YSMu9taK0k+72Jur0ub4Xjx4S5ZuKZ4iQeyL0lgCT2e88EO1zeHxnE72aEseCHzLRe18V22xX8N0jftYXRq2Bv+3eVh48u7vsuc1SAQ7/r+Kd3HeyyT34+A1cZRdhwKBDZ1m4ly3P0a4LDdGEUsacSGjowg7XN3QtncksPwP52u8xKv5zLonD/9cCSkK7hWXc3sZaWnUUx0VYfTPoTWZiuY6SFaOwDzkqaaH/QUWxizCRwME+OBf/AdWsap8ByV2V0S4KTYy5zMLPjRpih3149ZFMdf8vj7na+gVq82qRgbBQZ7rR33+ivnHVeA7ednWqwIBorezQ3O1PDwAnsqPNGUgkvPDDKfcBIAWWYvQ4=}
